* Potential Topic List

** NW3C: C2 Testing, Evaluation, and Identifiers
This project will involve the utilze the NW3C network and setup for the purpose of testing and 
evaluating different C2 frameworks. This will result in data to be further used in the NW3C project.
This topic is of interest as C2 frameworks vary in many ways while achieving the same goals. To be able to
test and investigate these frameworks on a full production environment is both cool and useful. The data
that will come from these tests can be used in real life investigations as well as for training purposes.

** Adversary Emulation Tool with Ali
This is an implementation project posted by Ali. The goal is to write and work on a threat emulation tool to
test the security posture against different threats actors. The tool will be written using a number of different
programming languages. This topic is of interest as I have a love of programming and to be able to program something
for security would be the best of both worlds for me. Writing an Adversary Emulation tool will also allow me to 
research APTs and how they work, resulting in a tool that can be used to test the security of tools that organizations
have in place to detect and prevent such attacks. 
